### ISSUE TITLE
Cannot access UI from IP:PORT

### ISSUE THREAD

**Issue by bocangr** [arrowhead-tools/mgmt-tool-js#5]
Hi,

I am facing one issue once the "npm start" is executed and the new screen appears with the management-tool.

When I enter the tood by IP:PORT, the UI charges for a moment and then I am redirected to this warning:

![image](https://user-images.githubusercontent.com/81161791/114184020-9b769d80-9944-11eb-9e7e-0c18135eb587.png)

This is my current .env file (I am sure the systems are located in those addresses):

![image](https://user-images.githubusercontent.com/81161791/114184813-4424fd00-9945-11eb-8529-e50f1afb93e7.png)

Thank you for your help. Kind regards,

Carlos

**Comment by tsvetlin** [comment]
Hello!

This bug was fixed last week, please pull the project.

**Comment by bocangr** [comment]
Hi,

Thank you for your answer!

I have repeated the installation steps from pull and I still have the same problem. I don't know if I am doing something wrong

![image](https://user-images.githubusercontent.com/81161791/114196457-a8e65480-9951-11eb-80f3-1f8e0e48e6c3.png)

Kind regards,

Carlos

**Comment by tsvetlin** [comment]
Hello! This issue was introduced by a modified key-value pair in one of the management interfaces.

Fixed with 4.4.0 release of the Management Tool
